import localFont from "next/font/local";
import "./globals.css";
import { ConfigProvider } from "antd";
import 'antd/dist/reset.css';

const geistSans = localFont({
  src: "/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const kanitFont = localFont({
  src: "/fonts/Kanit-Regular.ttf",
  variable: "--font-kanit",
  weight: "100 900",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kanitFont.variable} antialiased`}
      >
        <ConfigProvider theme={{ token: { fontFamily: 'var(--font-kanit)', }, }}>
          {children}
        </ConfigProvider>

      </body>
    </html>
  );
}
